apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: disks.localstorage.k8s.pgc.umn.edu
spec:
  group: localstorage.k8s.pgc.umn.edu
  names:
    kind: Disk
    listKind: DiskList
    plural: disks
    singular: disk
  scope: Namespaced
  version: v1alpha1
