apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filesystems.localstorage.k8s.pgc.umn.edu
spec:
  group: localstorage.k8s.pgc.umn.edu
  names:
    kind: Filesystem
    listKind: FilesystemList
    plural: filesystems
    singular: filesystem
  scope: Namespaced
  version: v1alpha1
