kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.operator.serviceaccount.name }}-{{ .Values.operator.serviceaccount.role }}-{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: {{ include "local-storage-operator.name" . }}
    helm.sh/chart: {{ include "local-storage-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: "{{ .Values.operator.serviceaccount.name }}-{{ .Release.Name }}"
  namespace: {{ .Values.namespace}}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.operator.serviceaccount.role }}-{{ .Release.Name }}"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: "{{ .Values.operator.serviceaccount.role }}-{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: {{ include "local-storage-operator.name" . }}
    helm.sh/chart: {{ include "local-storage-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  - persistentvolumes
  - events
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - localstorage.k8s.pgc.umn.edu
  resources:
  - '*'
  - disks
  - filesystems
  - storagepreparejobtemplates
  - storagepreparejobs
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.operator.serviceaccount.name }}-{{ .Release.Name }}"
  namespace: {{ .Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ include "local-storage-operator.name" . }}
    helm.sh/chart: {{ include "local-storage-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
